export const assessments = [
    {
        id: "anxiety", 
        name: "Anxiety Disorders",
        description: "In mental health, an anxiety disorder is characterized by persistent and excessive worry or fear that significantly interferes with daily life, encompassing various types like generalized anxiety disorder, panic disorder, and phobias. ",
        questions: [
            {
                question: "Do you often feel nervous, anxious, or on edge?",
                options: [{ text: "Never", value: 0 },
                    { text: "Sometimes", value: 1 },
                    { text: "Often", value: 2 },
                    { text: "Almost Always", value: 3 },],
            }, 
            {
                question: "Do you experience sudden feelings of panic without a clear cause?",
                options: [{ text: "Never", value: 0 },
                    { text: "Sometimes", value: 1 },
                    { text: "Often", value: 2 },
                    { text: "Almost Always", value: 3 },],
            },
            {
                question: "Do you worry too much about different things?",
                options: [{ text: "Never", value: 0 },
                    { text: "Sometimes", value: 1 },
                    { text: "Often", value: 2 },
                    { text: "Almost Always", value: 3 },],
            },
            {
                question: "Do you experience being so restless that it is hard to sit still?",
                options: [{ text: "Never", value: 0 },
                    { text: "Sometimes", value: 1 },
                    { text: "Often", value: 2 },
                    { text: "Almost Always", value: 3 },],
            },
            {
                question: "Do you feel afraid, as if something awful might happen?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
        ],
    },
    {
        id: "depression", 
        name: "Depression",
        description: "In mental health, depression, or depressive disorder, is a common and serious condition characterized by a persistent low mood and loss of interest or pleasure in activities, significantly impacting daily functioning. ",
        questions: [
            {
                question: "Have you lost interest or pleasure in doing things you normally enjoy?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            }, 
            {
                question: "Do you feel hopeless or worthless frequently?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Does it take a lot of effort to start working on something new.?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Do you feel lonely, and that people aren't that interested in you?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Do you have episodes of crying that are hard to stop.?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
        ],
    },
    {
        id: "bipolar", 
        name: "Bipolar Disorder",
        description: "Bipolar disorder, formerly known as manic-depressive illness, is a mental health condition characterized by extreme mood swings, including periods of elevated mood (mania or hypomania) and periods of depression. ",
        questions: [
            {
                question: "Do you have periods where you feel unusually energetic or elated?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            }, 
            {
                question: "Do you experience extreme mood swings without clear reasons?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Have you gone through periods where you got much less sleep than usual but didn’t really miss it??",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "You did things that were unusual for you or that other people might have thought were excessive, foolish, or risky?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "You were much more talkative or spoke much faster than usual?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
        ],
    },
    {
        id: "ptsd", 
        name: "Post-Traumatic Stress Disorder(PTSD)",
        description: "Post-traumatic stress disorder (PTSD) is a mental health condition that can develop after experiencing or witnessing a traumatic event, leading to persistent symptoms like reliving the trauma, avoidance, negative thoughts and mood changes, and heightened arousal. ",
        questions: [
            {
                question: "Do you have recurring, unwanted memories of a traumatic event?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            }, 
            {
                question: "Do you avoid places or things that remind you of the trauma?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Have you felt the guilt or unable to stop blaming yourself or others for the event(s) or any problems the event(s) may have caused?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Have you felt numb or detached from people, activities, or your surroundings?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Did you try hard not to think about the event(s) or went out of your way to avoid situations that reminded you of the event(s)?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
        ],
    },
    {
        id: "schizophrenia", 
        name: "Schizophrenia",
        description: "In mental health, schizophrenia is a chronic brain disorder characterized by disruptions in thought processes, perceptions, emotional responsiveness, and social interactions, often resulting in a loss of touch with reality, and can be both severe and disabling. ",
        questions: [
            {
                question: "Do you hear voices that others do not hear?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            }, 
            {
                question: "Do you have trouble distinguishing between reality and imagination?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Do you get the sense that others are controlling your thoughts and emotions?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Do you feel that you have powers that other people cannot understand or appreciate?",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
            {
                question: "Do you feel that you are being tracked, followed, or watched at home or outside? ",
                options: [{ text: "Never", value: 0 },
            { text: "Sometimes", value: 1 },
            { text: "Often", value: 2 },
            { text: "Almost Always", value: 3 },],
            },
        ],
    },
]